train:
  _target_: src.datasets.MixedDataset
  dataset:
    _target_: src.datasets.GRIDDataset
    dir: "data/audio"
    format: "wav"
    lufs: -23.0
    transform: null
  snr: [1, 2]
  lufs: 40000
  transform: null
