device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.MSEMetric
    metric:
      _target_: torch.nn.MSELoss
      reduction: "sum"
    device: ${metrics.device}
    name: "TRAIN_MSE" # just an example to see difference
  - _target_: src.metrics.SNRMetric
    metric:
      _target_: torchmetrics.audio.SignalNoiseRatio
    device: ${metrics.device}
    name: "TRAIN_SNR" # just an example to see difference
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.MSEMetric
    metric:
      _target_: torch.nn.MSELoss
      reduction: "sum"
    device: ${metrics.device}
    name: "MSE" # just an example to see difference
  - _target_: src.metrics.SNRMetric
    metric:
      _target_: torchmetrics.audio.SignalNoiseRatio
    device: ${metrics.device}
    name: "SNR" # just an example to see difference
