_target_: src.model.AudioVideoModel
video:
  _target_: src.model.PretrainedVideoModel
  model:
    _target_: src.model.lipreading.model.Lipreading
    modality: "video"
    hidden_dim: 256
    backbone_type: "resnet"
    num_classes: 500
    relu_type: "swish"
    tcn_options: {'num_layers': 4, 'kernel_size': [3, 5, 7], 'dropout': 0.2, 'dwpw': False, 'width_mult': 1}
    densetcn_options: {}
    width_mult: 1.0
    use_boundary: False
    extract_feats: True
  path: "pretrained/lrw_resnet18_mstcn_video.pth"
audio:
  _target_: src.model.ConvTasNetModel
  enc_dim: 512      # 512
  feature_dim: 128   # 128
  sr: 16000
  win: 2
  layer: 8
  stack: 3
  kernel: 3
  num_spk: 2
